### ISSUE TITLE
Can the colour of lines in "Graph View" be changed?

### ISSUE THREAD

**Issue by emeyedeejay** [RyzenFromFire/obsidian-phoenix#1]
Apologies if this is not the right way to ask this but ...

Can the colour of lines in "**Graph View**" be changed to something darker/more contrasty?

![image](https://github.com/RyzenFromFire/obsidian-phoenix/assets/8543879/eeb2ad4a-f3f1-4e85-bec5-5ba74a022fe0)

TIA - Love the rest of your theme!

**Comment by RyzenFromFire** [comment]
This is the best way to ask since I don't have any dedicated feature request system setup.

I generally don't use light mode outside of printing to PDF, so I can miss minor details like this. Thanks for pointing it out. If there's any other issues with light mode feel free to open another issue and I can fix it.

I added support for customizing this color. It won't be any different for dark theme, but in light theme it is now actually visible, and you can change the color it uses in `theme.css` if you want.

**Comment by emeyedeejay** [comment]
Thanks for sorting so quickly ... much better!

Just for interest - I am much more able to focus and see a crisper image in "light mode" than dark due to my astigmatism.

Some additional info here:

> **### Is dark mode better for your eyes?**
> While dark mode has a lot of benefits, it may not be better for your eyes. Using dark mode is helpful in that it’s easier on the eyes than a stark, bright white screen. However, using a dark screen requires your pupils to dilate which can make it harder to focus on the screen. 
> 
> Why does [eye dilation](https://www.allaboutvision.com/eye-care/eye-exams/eye-dilation-faqs/) make it harder to see? [When your pupils dilate](https://www.allaboutvision.com/conditions/dilated-pupils.htm), your vision becomes less clear. When your pupils constrict under bright light, your vision sharpens. Just like a camera, a smaller aperture provides greater depth of focus. For this reason, it may be more difficult for some people to clearly see screen details in dark mode.
> 
> People who have [myopia](https://www.allaboutvision.com/conditions/myopia.htm) or [astigmatism](https://www.allaboutvision.com/conditions/astigmatism.htm) also may experience halation (from the word “halo”). Halation occurs when light spreads past a certain boundary, creating a foggy or blurry appearance.
> 
> In other words, white letters can appear to bleed into a black background, making it more difficult to read, especially if the print is fine.

from: https://www.allaboutvision.com/digital-eye-strain/is-dark-mode-better-for-eyes/#:~:text=Just%20like%20a%20camera%2C%20a,the%20word%20%E2%80%9Chalo%E2%80%9D).
